name = "mymollu"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[[kv_namespaces]]
  binding = "KV_USERDATA"
  id = "a613bc84ffeb4362b3deaa05c617a7b3"
  preview_id = "49985f61319e42e6863fe6a66f3fc0fa"

[[kv_namespaces]]
  binding = "KV_SESSION"
  id = "757ca5d838364689af06edc372cd4c56"
  preview_id = "49985f61319e42e6863fe6a66f3fc0fa"

[[d1_databases]]
  binding = "DB"
  database_name = "mollulog"
  database_id = "8a001ff4-e56e-4836-8248-85e3ed37bde7"

[site]
  bucket = "./public"

[build]
  command = "yarn build"

[vars]
HOST = "https://mollulog.dodam.io"

# [secrets]
#   - SESSION_SECRET
#   - GOOGLE_CLIENT_SECRET
