name = "mollulog"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-08-15"

[placement]
  mode = "smart"

[site]
  bucket = "./public"

[build]
  command = "npm run worker:build"

[vars]
HOST = "https://mollulog.net"
STAGE = "prod"

# [secrets]
#   - SESSION_SECRET
#   - GOOGLE_CLIENT_SECRET
#   - SUPABASE_URL
#   - SUPABASE_KEY
#   - SUPERUSER_NAME

[triggers]
crons = ["30 * * * *"]

[[kv_namespaces]]
  binding = "KV_USERDATA"
  id = "a613bc84ffeb4362b3deaa05c617a7b3"

[[kv_namespaces]]
  binding = "KV_SESSION"
  id = "757ca5d838364689af06edc372cd4c56"

[[kv_namespaces]]
  binding = "KV_STATIC_DATA"
  id = "664d618c78334a4b90f1c1ba62e20e31"
