name = "mollulog"
pages_build_output_dir = "./build/client"

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-02"

[placement]
mode = "smart"

[vars]
HOST = "https://mollulog.net"
STAGE = "prod"

# [secrets]
#   - SESSION_SECRET
#   - GOOGLE_CLIENT_SECRET

[[kv_namespaces]]
binding = "KV_USERDATA"
id = "a613bc84ffeb4362b3deaa05c617a7b3"

[[d1_databases]]
binding = "DB"
database_name = "mollulog"
database_id = "7a71335f-8622-43c2-8b63-d842b6ef7761"
